# Generated by Django 5.2.17 on 2026-09-16 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Normative',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='Показатель')),
                ('value', models.JSONField(verbose_name='Значение')),
                ('source', models.CharField(max_length=500, verbose_name='Источник / допущение')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('company', models.CharField(blank=True, max_length=300, verbose_name='Производитель')),
                ('kind', models.CharField(blank=True, max_length=160, verbose_name='Тип')),
                ('subtype', models.CharField(blank=True, max_length=160, verbose_name='Подтип')),
                ('status', models.CharField(default='operation', max_length=50, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена, руб.')),
                ('applications', models.JSONField(default=list, verbose_name='Отрасли и сценарии')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('sources', models.JSONField(default=list, verbose_name='Источники')),
                ('observations', models.JSONField(default=list, verbose_name='Исходные записи')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Каталог решений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('object_type', models.CharField(default='warehouse', max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.project')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('project', 'revision'), name='unique_project_revision')],
            },
        ),
    ]
